### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by d3netxer** [ToeBee/ChangesetMD#24] opened 2016-10-26 02:24 UTC
I am trying the replication out and getting an error

```
parsed 22
opening replication file at http://planet.openstreetmap.org/replication/changesets/002/065/033.osm.gz
parsing complete
parsed 18
opening replication file at http://planet.openstreetmap.org/replication/changesets/002/065/034.osm.gz
parsing complete
parsed 18
opening replication file at http://planet.openstreetmap.org/replication/changesets/002/065/035.osm.gz
parsing complete
parsed 14
opening replication file at http://planet.openstreetmap.org/replication/changesets/002/065/036.osm.gz
error during replication
[Errno 104] Connection reset by peer
```

anybody know why this is or how to solve it?

**Comment by ToeBee** [comment] 2016-10-26 03:16
Generally this indicates a problem with your network. Does it happen repeatedly on the same file? And can you download the file in the message immediately before the error using your browser?

**Comment by d3netxer** [comment] 2016-10-26 03:29
no it is unpredictable how many files it can open and parse before the error occurs. I tired putting a time delay, but that doesn't seem to be doing much. 

yes, I can download the file in the message immediately before the error using my browser

**Comment by ToeBee** [comment] 2016-10-26 22:49
Sounds like an unreliable network between you and planet.osm.org. Not much my code can do about that. How is it failing? I know in some failure modes you have to go into the database and clear the process status manually. I **think** that only happens when something goes wrong during parsing of the XML though so hopefully you can just restart the process and it will pick up where you left off on the last run?

**Comment by d3netxer** [comment] 2016-10-27 00:54
When it fails, it seems to fail before it starts parsing the file. Then when the command is restarted it tries to download the same file again, if that is successful, then it continues. So it seems to just pick off where if left off.

**Comment by ToeBee** [comment] 2016-10-30 17:50
Well since my code is working as intended on a flaky network, I'm closing this issue.

**Closed by ToeBee** 2016-10-30 17:50 UTC
